version: "3.7"

services:

  php:
    build:
      context: docker/php
    container_name: ${APP_NAME}-php
    working_dir: /application
    volumes:
      - ./:/application
    links:
      - mysql
    networks:
      - backend-network

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    working_dir: /application
    volumes:
      - ./:/application
      - ./docker/nginx/${APP_ENV}/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
    networks:
      - backend-network

  mysql:
    image: mysql:8.0.25
    container_name: ${APP_NAME}-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: emporio
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
